apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: academy-api
  template:
    metadata:
      labels:
        app: academy-api
    spec:
      containers:
        - name: academy-api
          image: liceu/academy-api:latest
          ports:
            - containerPort: 3000
